export interface MusicLibraryTrack {
  id: string;
  title: string;
  artist: string;
  mood: string;
}

// Metadata only: playback remains local-first and never bundles copyrighted audio.
export const MUSIC_LIBRARY_TRACKS: readonly MusicLibraryTrack[] = [
  ['blinding-lights', 'Blinding Lights', 'The Weeknd', '夜行'],
  ['save-your-tears', 'Save Your Tears', 'The Weeknd', '回望'],
  ['starboy', 'Starboy', 'The Weeknd', '霓虹'],
  ['as-it-was', 'As It Was', 'Harry Styles', '漂浮'],
  ['watermelon-sugar', 'Watermelon Sugar', 'Harry Styles', '晴日'],
  ['adore-you', 'Adore You', 'Harry Styles', '温柔'],
  ['anti-hero', 'Anti-Hero', 'Taylor Swift', '自省'],
  ['cruel-summer', 'Cruel Summer', 'Taylor Swift', '盛夏'],
  ['cardigan', 'cardigan', 'Taylor Swift', '旧梦'],
  ['espresso', 'Espresso', 'Sabrina Carpenter', '轻快'],
  ['please-please-please', 'Please Please Please', 'Sabrina Carpenter', '俏皮'],
  ['feather', 'Feather', 'Sabrina Carpenter', '轻盈'],
  ['flowers', 'Flowers', 'Miley Cyrus', '自持'],
  ['midnight-sky', 'Midnight Sky', 'Miley Cyrus', '远景'],
  ['used-to-be-young', 'Used To Be Young', 'Miley Cyrus', '回忆'],
  ['levitating', 'Levitating', 'Dua Lipa', '跃动'],
  ['dont-start-now', "Don't Start Now", 'Dua Lipa', '清醒'],
  ['new-rules', 'New Rules', 'Dua Lipa', '边界'],
  ['bad-guy', 'bad guy', 'Billie Eilish', '冷感'],
  ['lovely', 'lovely', 'Billie Eilish', '薄雾'],
  ['birds-of-a-feather', 'BIRDS OF A FEATHER', 'Billie Eilish', '靠近'],
  ['drivers-license', "drivers license", 'Olivia Rodrigo', '失重'],
  ['vampire', 'vampire', 'Olivia Rodrigo', '暗涌'],
  ['deja-vu', 'deja vu', 'Olivia Rodrigo', '回声'],
  ['happier-than-ever', 'Happier Than Ever', 'Billie Eilish', '释放'],
  ['love-story', 'Love Story', 'Taylor Swift', '叙事'],
  ['one-kiss', 'One Kiss', 'Calvin Harris & Dua Lipa', '脉冲'],
  ['feel-so-close', 'Feel So Close', 'Calvin Harris', '开阔'],
  ['summer', 'Summer', 'Calvin Harris', '暖光'],
  ['get-lucky', 'Get Lucky', 'Daft Punk', '夜色'],
  ['instant-crush', 'Instant Crush', 'Daft Punk', '机械心'],
  ['lose-yourself', 'Lose Yourself', 'Eminem', '推进'],
  ['without-me', 'Without Me', 'Eminem', '锋利'],
  ['mockingbird', 'Mockingbird', 'Eminem', '叙述'],
  ['seven-nation-army', 'Seven Nation Army', 'The White Stripes', '低频'],
  ['dreams', 'Dreams', 'Fleetwood Mac', '漂流'],
  ['everywhere', 'Everywhere', 'Fleetwood Mac', '晴朗'],
  ['take-on-me', 'Take On Me', 'a-ha', '复古'],
  ['running-up-that-hill', 'Running Up That Hill', 'Kate Bush', '上升'],
  ['enjoy-the-silence', 'Enjoy the Silence', 'Depeche Mode', '静谧'],
  ['midnight-city', 'Midnight City', 'M83', '城市'],
  ['the-less-i-know', 'The Less I Know The Better', 'Tame Impala', '迷离'],
  ['borderline', 'Borderline', 'Tame Impala', '边缘'],
  ['yellow', 'Yellow', 'Coldplay', '微光'],
  ['viva-la-vida', 'Viva La Vida', 'Coldplay', '远征'],
  ['a-sky-full-of-stars', 'A Sky Full of Stars', 'Coldplay', '星群'],
  ['somebody-that-i-used-to-know', 'Somebody That I Used to Know', 'Gotye', '断片'],
  ['riptide', 'Riptide', 'Vance Joy', '海风'],
  ['electric-feel', 'Electric Feel', 'MGMT', '脉动'],
  ['safe-and-sound', 'Safe And Sound', 'Capital Cities', '安静'],
].map(([id, title, artist, mood]) => ({
  id: id ?? '',
  title: title ?? '',
  artist: artist ?? '',
  mood: mood ?? '',
}));
